---

- name: Install nginx
  apt:
    name:
      - nginx
    state: latest
    update_cache: yes
    cache_valid_time: 600
  notify:
    - Restart nginx

- name: Remove the default sites
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html

- name: Copy the nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/nginx -t -c %s

- name: Enable the nginx service
  systemd:
    name: nginx.service
    enabled: yes
    state: started
