---

- name: Set up the site
  template:
    src: pihole.conf.j2
    dest: /etc/nginx/sites-available/pihole.conf
    owner: root
    group: root
    mode: 0644

- name: Enable the site
  file:
    path: /etc/nginx/sites-enabled/pihole.conf
    src: /etc/nginx/sites-available/pihole.conf
    state: link

- name: Validate nginx config
  command:
    cmd: /usr/sbin/nginx -t

- name: Reload nginx
  systemd:
    name: nginx.service
    state: reloaded
