---

- name: Install certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Register certbot
  block:
    - name: Register certbot
      command:
        cmd: "/usr/bin/certbot register --non-interactive --agree-tos --email {{ email | quote }}"
        creates: /etc/letsencrypt/.registered

    - name: Create the .registered file
      file:
        path: /etc/letsencrypt/.registered
        state: touch
        owner: root
        group: root
        mode: 0644

- name: Generate a TLS certificate
  command:
    cmd: >
      /usr/bin/certbot certonly
        --nginx
        --non-interactive
        --key-type ecdsa
        --domain *.{{ domain | quote }}
    creates: "/etc/letsencrypt/live/{{ domain }}"

- name: Enable the certbot timer
  systemd:
    name: certbot.timer
    enabled: yes
    state: started
