---

- name: Server config
  hosts: dale
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter the admin user password"
      private: yes
      unsafe: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: "{{ admin_username }}"
  roles:
    - role: init_common
      tags: [ init ]

    - role: sshd
      tags: [ security, sshd ]
    - role: wireguard
      tags: [ security, wireguard ]
    - role: wireguard_client
      tags: [ security, wireguard_client ]
    - role: nftables
      tags: [ security, nftables ]

    - role: unbound
      tags: [ services, unbound ]
    - role: unbound_blocking
      tags: [ services, unbound_blocking ]
    - role: overlay_network
      tags: [ services, overlay_network ]
    - role: nginx
      tags: [ services, nginx ]
    - role: tls
      tags: [ services, tls ]
    - role: website
      tags: [ services, website ]
    - role: git
      tags: [ services, git ]
    - role: rss
      tags: [ services, rss ]
