---

- include_role:
    name: nginx_site
  vars:
    public: yes
    site_name: "{{ domain }}"
    site_config: ./templates/website.conf.j2

- name: Create the webroot
  file:
    path: "/var/www/{{ domain }}"
    state: directory
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: 0755
