---

- name: Install unbound
  apt:
    name:
      - unbound
    state: latest
    update_cache: yes
    cache_valid_time: 600
  notify:
    - Restart unbound

- name: Clear the default unbound configuration
  file:
    path: /etc/unbound/unbound.conf.d
    state: absent

- name: Create the unbound configuration subdirectory
  file:
    path: /etc/unbound/unbound.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

# The unbound-anchor command returns 0 if no update is necessary and 1 when
# an update was made.
- name: Download the initial root trust anchor for DNSSEC validation
  command: /usr/sbin/unbound-anchor -a /etc/unbound/trusted-key.key
  register: download_anchor
  failed_when: "download_anchor.rc != 0 and download_anchor.rc != 1"
  notify:
    - Reload unbound

- name: Allow updating the root anchor by the unbound user
  file:
    path: "{{ item }}"
    owner: root
    group: unbound
    mode: 0775
  loop:
    - /etc/unbound
    - /etc/unbound/trusted-key.key

- name: Copy the unbound config
  block:
    - name: Copy the forward-zone config
      copy:
        src: unbound-forward-zone.conf
        dest: /etc/unbound/unbound.conf.d/unbound-forward-zone.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy the main config
      template:
        src: unbound.conf.j2
        dest: /etc/unbound/unbound.conf
        owner: root
        group: root
        mode: 0644
        validate: /usr/sbin/unbound-checkconf %s
      notify:
        - Restart unbound

- name: Enable the unbound service
  systemd:
    name: unbound.service
    enabled: yes
    state: started
