---

- name: Update the system
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes

- name: Install the necessary packages
  apt:
    name:
      - sudo
      - unattended-upgrades
    state: latest

- name: Create the admin user
  user:
    name: "{{ admin_username }}"
    password: "{{ admin_password | password_hash('sha512') }}"
    update_password: on_create
    comment: The main user
    state: present
    shell: /bin/bash
    groups:
      - sudo
    append: yes
  register: admin_created

- name: Expire the admin password
  command: "/usr/bin/chage -d 0 {{ admin_username }}"
  when: admin_created.changed

- name: Copy the admin SSH key
  ansible.posix.authorized_key:
    user: "{{ admin_username }}"
    key: "{{ lookup('file', ssh_admin_pubkey_file) }}"

- name: Enable unattended updates
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
