---

- name: Install git
  apt:
    name:
      - git
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Add git-shell to shells
  lineinfile:
    path: /etc/shells
    line: /usr/bin/git-shell
    state: present

- name: Check if the git user exists
  command: /usr/bin/getent passwd git
  register: git_user_exists
  ignore_errors: yes

- name: Create the git user if it does not exist
  user:
    name: git
    password: "{{ git_password | password_hash('sha512') }}"
    update_password: on_create
    comment: The git user
    state: present
    shell: /usr/bin/git-shell
    system: yes
  when: git_user_exists.rc != 0

- name: Allow the main user to access the git directory
  user:
    name: "{{ admin_username }}"
    groups:
      - git
    append: yes

- name: Add access keys
  lineinfile:
    path: "/home/git/.ssh/authorized_keys"
    line: "{{ item }}"
    state: present
  loop:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBaTcR5f4bbzG6JmuyFfMAEuQYRmWzt518BlBIbyr1MK Git key for the VPS
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOCmYsyCuOmqW1utcZvBWYIzZnDEXUjmg/YpdcOWudF5 Android key
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDQQQ7zAwXCpFVWNGnhOck8GqOELWAHCy5NrH9nyxjzU home_git
