---

- name: Install git
  apt:
    name:
      - git
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Add git-shell to shells
  lineinfile:
    path: /etc/shells
    line: /usr/bin/git-shell
    state: present

- name: Check if the git user exists
  command: /usr/bin/getent passwd git
  register: git_user_exists
  ignore_errors: yes

- name: Create the git user if it does not exist
  user:
    name: git
    comment: The git user
    state: present
    create_home: yes
    shell: /usr/bin/git-shell
    system: yes
  when: git_user_exists.rc != 0

- name: Allow the main user to access the git directory
  user:
    name: "{{ admin_username }}"
    groups:
      - git
    append: yes

- name: Add access keys
  block:
    - name: Make sure /home/git/.ssh exists
      file:
        path: /home/git/.ssh
        state: directory
        owner: git
        group: git
        mode: 0755

    - name: Make sure /home/git/.ssh/authorized_keys exists
      file:
        path: /home/git/.ssh/authorized_keys
        state: touch
        owner: git
        group: git
        mode: 0600

    - name: Copy keys
      lineinfile:
        path: "/home/git/.ssh/authorized_keys"
        line: "{{ item }}"
        state: present
      loop: "{{ ssh_keys_git }}"
