- name: Ensure the sites directory exists
  file:
    path: /etc/nginx/sites-config
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy the site config ({{ site_name }})
  template:
    src: "{{ site_config }}"
    dest: "/etc/nginx/sites-config/{{ site_name }}.conf"
    owner: root
    group: root
    mode: 0755

- name: Create the public site wrapper ({{ site_name }})
  template:
    src: public.conf.j2
    dest: "/etc/nginx/sites-available/{{ site_name }}.conf"
    owner: root
    group: root
    mode: 0755
  when: public

- name: Create the private site wrapper ({{ site_name }})
  template:
    src: private.conf.j2
    dest: "/etc/nginx/sites-available/{{ site_name }}.conf"
    owner: root
    group: root
    mode: 0755
  when: not public

- name: Enable the site config ({{ site_name }})
  file:
    path: "/etc/nginx/sites-enabled/{{ site_name }}.conf"
    src: "/etc/nginx/sites-available/{{ site_name }}.conf"
    state: link

- name: Validate nginx config
  command:
    cmd: /usr/sbin/nginx -t

- name: Reload nginx
  systemd:
    name: nginx.service
    state: reloaded
