---

- name: Install python3-venv
  apt:
    name:
      - python3-venv
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Enable unbound remote control
  command:
    cmd: /usr/sbin/unbound-control-setup -d /etc/unbound

- name: Copy the unbound remote control config
  block:
    - name: Copy the config
      copy:
        src: unbound-remote-control.conf
        dest: /etc/unbound/unbound.conf.d/unbound-remote-control.conf
        owner: root
        group: root
        mode: 0644

    - name: Validate the main unbound config
      command:
        cmd: /usr/sbin/unbound-checkconf

- name: Copy the DNS blocklist
  copy:
    src: dns-blocklist
    dest: /opt
    owner: root
    group: root
    mode: 0700

- name: Define a virtual environment for running the script
  pip:
    name: requests
    virtualenv: /opt/dns-blocklist/venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Set up a blocklist-filling cronjob
  cron:
    user: root
    minute: 0
    hour: 5
    day: "*"
    month: "*"
    dow: 0
    name: Fetch unbound blocklist
    job: /opt/dns-blocklist/venv/bin/python3 /opt/dns-blocklist/fetch-blocklist.py -s /opt/dns-blocklist/blocklist-sources.txt -w /opt/dns-blocklist/whitelist.txt -l /opt/dns-blocklist/fetch-blocklist.log

- name: Fill the blocklist for the first time
  shell:
    cmd: /opt/dns-blocklist/venv/bin/python3 /opt/dns-blocklist/fetch-blocklist.py -s /opt/dns-blocklist/blocklist-sources.txt -w /opt/dns-blocklist/whitelist.txt -l /opt/dns-blocklist/fetch-blocklist.log

