---

- name: Install packages
  apt:
    name:
      - unzip
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Create the rss user
  user:
    name: rss
    comment: The RSS user
    state: present
    create_home: no
    shell: /usr/bin/false
    system: yes

- name: Install yarr
  block:
    - name: Stop the yarr service if it exists
      systemd:
        name: yarr.service
        state: stopped
      ignore_errors: yes

    - name: Create the yarr directory
      file:
        path: /opt/yarr
        state: directory
        owner: rss
        group: rss
        mode: 0755

    - name: Fetch and unpack yarr
      unarchive:
        src: "{{ yarr.archive }}"
        dest: /opt/yarr
        remote_src: yes
        owner: rss
        group: rss

    - name: Copy the yarr service file
      template:
        src: yarr.service.j2
        dest: /etc/systemd/system/yarr.service
        owner: root
        group: root
        mode: 0644
      register: yarr_service

    - name: Reload daemons
      systemd:
        daemon_reload: yes
      when: yarr_service.changed

    - name: Enable the yarr service
      systemd:
        name: yarr.service
        enabled: yes
        state: started

- include_role:
    name: nginx_site
  vars:
    public: no
    site_name: rss.home.arpa
    site_config: ./templates/rss.conf.j2
