---

- name: Raspberry config
  hosts: bob
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter the admin user password"
      private: yes
      unsafe: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: "{{ admin_username }}"
  roles:
    - role: init_common
      tags: [ init, init_common ]
    - role: init_raspberry
      tags: [ init, init_raspberry ]

    - role: sshd
      tags: [ security, sshd ]
    - role: wireguard
      tags: [ security, wireguard ]
    - role: nftables
      tags: [ security, nftables ]

    - role: nginx
      tags: [ services, nginx ]
    - role: unbound
      tags: [ services, unbound ]
    - role: pihole
      tags: [ services, pihole ]
    - role: navidrome
      tags: [ services, navidrome ]
    - role: ip_forwarding
      tags: [ services, ip_forwarding ]
