---

- name: Install qrencode
  apt:
    name:
      - qrencode
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Check if client configuration exists
  lineinfile:
    path: /etc/wireguard/wg0.conf
    regexp: "^# First$"
    state: absent
  check_mode: yes
  changed_when: no
  register: wg_client

- name: Copy the add-peer script
  copy:
    src: add-peer
    dest: /usr/local/bin/add-peer
    owner: root
    group: root
    mode: 0700

- name: Create a peer
  shell:
    cmd: |
      endpoint=$(/usr/sbin/ip -4 addr show dev {{ wan_interface | quote }} \
        | /usr/bin/awk '/inet/ {print $2}' \
        | /usr/bin/cut -d/ -f1)

      /usr/local/bin/add-peer \
        -n First \
        -4 {{ vpn_client_ipv4 | quote }} \
        -6 {{ vpn_client_ipv6 | quote }} \
        -e "$endpoint":{{ vpn_port | quote }} \
        -c /etc/wireguard/wg0.conf \
        -t access \
        > /etc/wireguard/peer.conf
  when: not wg_client.found
  notify:
    - Reload wireguard

- name: Fetch the peer config
  fetch:
    src: /etc/wireguard/peer.conf
    dest: "{{ ansible_ssh_host }}/peer.conf"
    flat: yes
  when: not wg_client.found

- name: Remove the peer config
  file:
    path: /etc/wireguard/peer.conf
    state: absent
  when: not wg_client.found
