---

- name: Update the system
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
    use: systemd

- name: Set the timezone
  command:
    cmd: "timedatectl set-timezone {{ timezone | quote }}"

- name: Install utilities
  apt:
    name:
      - ca-certificates
      - rsync
      - unattended-upgrades
      - vim
      - tmux
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Enable unattended upgrades
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
