---

- name: Update the system
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes

- name: Install the necessary packages
  apt:
    name:
      - unattended-upgrades
    state: latest

- name: Enable unattended updates
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
