---

- name: Install wireguard
  apt:
    name:
      - wireguard
      - wireguard-tools
    state: latest
    update_cache: yes
    cache_valid_time: 600
  notify:
    - Restart wireguard

- name: Check if configuration exists
  stat:
    path: /etc/wireguard/wg0.conf
  register: wg_conf

- name: Generate the server key
  shell:
    cmd: |
      umask 0077

      /usr/bin/mkdir -p /etc/wireguard/keys

      /usr/bin/wg genkey \
        | /usr/bin/tee /etc/wireguard/keys/wg0_private.key \
        | /usr/bin/wg pubkey \
        > /etc/wireguard/keys/wg0_public.key

      umask 0022
  when: wg_conf is not defined or not wg_conf.stat.exists

# Needed for the server config template.
- name: Register the server key
  command:
    cmd: /usr/bin/cat /etc/wireguard/keys/wg0_private.key
  register: vpn_private_key
  when: wg_conf is not defined or not wg_conf.stat.exists

- name: Copy the wireguard config
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  when: wg_conf is not defined or not wg_conf.stat.exists

- name: Enable the wireguard service
  systemd:
    name: wg-quick@wg0.service
    enabled: yes
    state: started

- name: Start sshd after wireguard
  block:
  - name: Ensure the sshd service directory exists
    file:
      # Debian-based systems name the sshd service directory 'ssh.service.d'.
      path: /etc/systemd/system/ssh.service.d
      state: directory
      recurse: yes
      owner: root
      group: root
      mode: 0755

  - name: Add a systemd override
    copy:
      content: |
        [Unit]
        After=
        After=network.target auditd.service wg-quick@wg0.service
        Requires=
        Requires=wg-quick@wg0.service
      dest: /etc/systemd/system/ssh.service.d/override.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - Reload daemons
      - Restart sshd

- name: Remove the generated keys
  file:
    path: /etc/wireguard/keys
    state: absent
  when: wg_conf is not defined or not wg_conf.stat.exists
