---

- name: Copy the sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -T -f %s
  notify:
    - Reload sshd

- name: Deactivate short Diffie-Hellman moduli
  shell:
    cmd: /usr/bin/awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp && /usr/bin/mv /etc/ssh/moduli.tmp /etc/ssh/moduli

- name: Add access keys
  block:
    - name: Make sure /home/{{ admin_username }}/.ssh exists
      file:
        path: "/home/{{ admin_username }}/.ssh"
        state: directory
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: 0755

    - name: Make sure /home/{{ admin_username }}/.ssh/authorized_keys exists
      file:
        path: "/home/{{ admin_username }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: 0600

    - name: Copy keys
      lineinfile:
        path: "/home/{{ admin_username }}/.ssh/authorized_keys"
        line: "{{ item }}"
        state: present
      loop: "{{ ssh_keys_admin }}"
