---

- name: Copy the sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -T -f %s
  notify:
    - Reload sshd

- name: Deactivate short Diffie-Hellman moduli
  shell:
    cmd: /usr/bin/awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp && /usr/bin/mv /etc/ssh/moduli.tmp /etc/ssh/moduli

- name: Add access keys
  lineinfile:
    path: "/home/{{ admin_username | quote }}/.ssh/authorized_keys"
    line: "{{ item }}"
    state: present
  loop:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPrK/gGoC5nX+u82z2N/8u+gd/yMJrb6pMln/zJJjG4w Access key for the VPS
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDXh5D6Rhl/ORiXXW+BYZN3+/OcyMdPKTI+BM7HQI8MN home
