name: 'Flake check'
on:
  push:
jobs:
  flake-check:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
    runs-on: '${{ matrix.os }}'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'
      - name: 'Install Nix'
        uses: 'DeterminateSystems/nix-installer-action@v19'
      - name: 'Give GitHub Actions access to infra-secrets'
        uses: 'webfactory/ssh-agent@v0.9.1'
        with:
          ssh-private-key: '${{ secrets.INFRA_SECRETS_DEPLOY_KEY }}'
      - name: 'Run Nix flake checker'
        uses: 'DeterminateSystems/flake-checker-action@v12'
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
      - name: 'Run checks'
        run: 'nix flake check'
        # Disabled because Nix Catppuccin like to break stuff without warning,
        # causing the checks to always fail on an aarch64-darwin builder.
        # See https://github.com/catppuccin/nix/issues/437 and
        # https://github.com/catppuccin/nix/issues/392.
        if: matrix.os != 'macos-latest'
