name: 'Flake update'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  flake-update:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v6'
      - name: 'Install Nix'
        uses: 'DeterminateSystems/nix-installer-action@v22'
      - name: 'Update Nix Flake Lock'
        uses: 'DeterminateSystems/update-flake-lock@v28'
        with:
          token: '${{ secrets.FLAKE_UPDATE_RUN_CI_TOKEN }}'
