name: 'Flake update'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  flake-update:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Install Nix'
        uses: 'DeterminateSystems/nix-installer-action@v16'

      - name: 'Setup Magic Nix Cache'
        uses: 'DeterminateSystems/magic-nix-cache-action@v8'

      - name: 'Give GitHub Actions access to infra-secrets'
        uses: 'webfactory/ssh-agent@v0.9.0'
        with:
          ssh-private-key: '${{ secrets.INFRA_SECRETS_DEPLOY_KEY }}'

      - name: 'Update flake.lock'
        run: 'nix flake update'

      - name: 'Nix Flake Checker'
        uses: 'DeterminateSystems/flake-checker-action@v9'
        with:
          ignore-missing-flake-lock: false
          fail-mode: true

      - name: 'Commit & push flake.lock'
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '7727887+tomaskala@users.noreply.github.com'

          git add flake.lock
          git commit -m 'Github Actions: Update flake.lock'
          git push
